- hosts: frontends
  gather_facts: false
  tasks:
  - name: Use Uri module for wrting smoke test.
    uri:
      url: "http://localhost"
      return_content: yes
    register: webpage

  - name: Fail if 'Ansible has done its job' is not in the page content
    fail:
      msg: Did not find the proper string in the test.
    when: "'Ansible has done its job' not in webpage.content"
    tags:
      - aws.smoke
