---
# tasks file for db-tier

- name: Install Packages for DB Tier
  package:
    name: "{{ item }}"
    state: latest
  with_items: "{{ postgres_packages }}"

- name: Enable Postgres at boot and if required, initialize the DB.
  service:
    name: postgresql
    enabled: yes
  notify: initialize postgres